OLLAMA_MODELS: [qwen3:1.7b]

# Tavily Search API (For Orchestrator)
TAVILY_API_KEY: ""

# Template dir
ORCHESTRATOR_TEMPLATE_DIR: "agents/orchestrator/templates"
GENERATOR_TEMPLATE_DIR: "agents/generator/templates"
EVALUATOR_TEMPLATE_DIR: "agents/evaluator/templates"

# Languages
SUPPORTED_LANGUAGES: ["vietnamese", "english"]

# Topic types for Orchestrator
TOPIC_TYPES:
  - food_nutrition
  - disease_warning
  - travel_adventure
  - business_enterprise
  - lifestyle_office
  - holiday_event

# Post types for Generator/Evaluator
POST_TYPES:
  - health_nutrition
  - disease_warning
  - travel_adventure
  - business_enterprise
  - lifestyle_office
  - holiday_event

# Some default settings
DEFAULT_LANGUAGE: "vietnamese"
DEFAULT_TOPIC_TYPE: "food_nutrition"
DEFAULT_POST_TYPE: "health_nutrition"

# System configuration
MAX_ITERATIONS: 3
PASS_THRESHOLD: 0.75

# For RAG
# OPENAI_API_KEY: ""
# COHERE_API_KEY: ""
# DATASET_PATH: data_campaign